package Jeux;


/**
* Jeux/IConnexionRemoteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Jeux.idl
* lundi 13 juin 2016 18 h 17 CEST
*/

public interface IConnexionRemoteOperations 
{
  boolean seConnecter ();
  boolean seDeconnecter ();
} // interface IConnexionRemoteOperations
