package Jeux;


/**
* Jeux/IJoueurRemoteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Jeux.idl
* lundi 13 juin 2016 18 h 17 CEST
*/

public interface IJoueurRemoteOperations 
{
  Jeux.Joueur creerUnCompte ();
  String voirLeScore (Jeux.Joueur joueur);
  Jeux.Joueur[] voirClassementJoueur ();
  Jeux.Joueur[] voirJoueursConnectes ();
} // interface IJoueurRemoteOperations
