package Jeux;


/**
* Jeux/IJoueurRemoteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Jeux.idl
* samedi 18 juin 2016 17 h 40 CEST
*/

public interface IJoueurRemoteOperations 
{
  void creerUnCompte (String pseudo, String mdp) throws Exception;
  String voirLeScore (Jeux.Joueur joueur);
  void voirClassementJoueur () throws Exception;
  Jeux.Joueur[] voirJoueursConnectes ();
} // interface IJoueurRemoteOperations
