package Jeux;


/**
* Jeux/IJoueurRemoteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Jeux.idl
* samedi 18 juin 2016 19 h 07 CEST
*/

public interface IJoueurRemoteOperations 
{
  String creerUnCompte (String pseudo, String mdp) throws Exception;
  String voirLeScore (Jeux.Joueur joueur) throws Exception;
  String voirClassementJoueur () throws Exception;
  String voirJoueursConnectes ();
  String vueJoueur ();
} // interface IJoueurRemoteOperations
