package Jeux;


/**
* Jeux/IPartieRemoteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Jeux.idl
* samedi 18 juin 2016 19 h 07 CEST
*/

public interface IPartieRemoteOperations 
{
  String partiesEnAttente ();
  String creerPartie (int nbJoueurs);
  String voirJoueursEnPartie (Jeux.Partie partie);
  String vuePartie ();
} // interface IPartieRemoteOperations
