package Jeux;


/**
* Jeux/IPartieRemoteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Jeux.idl
* samedi 18 juin 2016 17 h 40 CEST
*/

public interface IPartieRemoteOperations 
{
  Jeux.Partie[] partiesEnAttente ();
  Jeux.Partie creerPartie (int nbJoueurs);
  Jeux.Joueur[] voirJoueursEnPartie (Jeux.Partie partie);
} // interface IPartieRemoteOperations
