module Jeux {

    struct Joueur{
        long id;
        string pseudo;
        string password;
        string totalScore;
    };
    typedef sequence<Joueur> listeJoueurs;
    typedef sequence<Joueur> listeClassement;

    struct Partie{
        long id;
        long nbJoueurs;
        long nbCarte;
        listeJoueurs joueurs;

    };
    typedef sequence<Partie> listePartiesEnAttente;

    interface IConnexionRemote{
         boolean seConnecter();
         boolean seDeconnecter();
    };
    interface IJoueurRemote{
        Joueur creerUnCompte();
        string voirLeScore( in Joueur joueur);
        listeClassement voirClassementJoueur();
        listeJoueurs voirJoueursConnectes();
    };
    interface IPartieRemote{
        listePartiesEnAttente partiesEnAttente();
        Partie creerPartie();
        listeJoueurs voirJoueursEnPartie( in Partie partie);
    };

};