module Jeux {

    struct Joueur{
        long id;
        string pseudo;
        string password;
        string totalScore;
    };
    typedef sequence<Joueur> listeJoueurs;
    typedef sequence<Joueur> listeClassement;

    struct Partie{
        long id;
        long nbJoueurs;
        long nbCarte;
        listeJoueurs joueurs;

    };
    typedef sequence<Partie> listePartiesEnAttente;

    struct Carte{
            string valeur;
    };

    interface IConnexionRemote{
         string seConnecter( in string pseudo, in string mdp);
         string seDeconnecter(in Joueur joueur);
    };
    interface IJoueurRemote{
        string creerUnCompte( in string pseudo, in string mdp);
        string voirLeScore( in Joueur joueur);
        string voirClassementJoueur();
        string voirJoueursConnectes();
        string vueJoueur();
    };
    interface IPartieRemote{
        string partiesEnAttente();
        string creerPartie(in long nbJoueurs);
        string voirJoueursEnPartie( in Partie partie);
        string vuePartie();
    };

};